### ISSUE TITLE
Jikan V3 now deprecated

### ISSUE THREAD

**Issue by Shane-stage** [abhinavk99/jikanpy#100]
jikanpy now only returns 410 errors from Jikan. Could we get this utility updated to the v4 api? 

Thank you!

**Comment by seanbreckenridge** [comment]
See #94 

There was a plan to move over to using the openapi schema to auto generate a client, but there have been a few issues with that.

Otherwise, migrating to v4 would require a full rewrite and currently no plan to do that.

There was a [post on the discord](https://discord.com/channels/460491088004907029/461020417998454785/1015986391244611604) a few months ago, but no responses afaik

So -- I think for now to use v4, should use [`requests`](https://requests.readthedocs.io/en/latest/) and see the [docs](https://docs.api.jikan.moe/) to make the requests manually

**Comment by abhinavk99** [comment]
Fixed in #101
