### ISSUE TITLE
push new version to pypi

### ISSUE THREAD

**Issue by seanbreckenridge** [abhinavk99/jikanpy#103]
@Chris-Peterson444 I think since this is such a breaking change, you can push to a new name on pypi so automatic upgrades dont lead to breaking peoples code, like `jikanpy_v4`, and update the readme to that

**Comment by Chris-Peterson444** [comment]
You bring up a good point, I hadn't considered there might still be people self-hosting with Jikan v3. I can push this version to a new name on pypi, but then maybe we should have a separate branch here to differentiate between the two versions.

**Comment by Chris-Peterson444** [comment]
So two things have come up that I'd like some input on:

1. Do we want the package name to be changed to `jikanpy_v4` just on pypi or do we also want python to recognize the new name (i.e. do we want to be able to still import as `jikanpy` or as `jikanpy_v4` ) ?

2. If I'm uploading the package to pypi, should I change the author name and email in setup.py? I'd be happy to help maintain things but I'm not sure what the etiquette here is. I supposed this one is more directed to @abhinavk99 since he is the current author, but @seanbreckenridge I'd be happy to hear your advice as well.

**Comment by seanbreckenridge** [comment]
1) I think `jikanpy_v4` just on `pypi` -- I think it should still import from `jikanpy`, people are very used to doing that

should probably add something like this to the readme:

```python
# uninstall old jikanpy
python3 -m pip uninstall -y jikanpy
python3 -m pip install --no-cache-dir jikanpy_v4
```

just to avoid any possible caching/install issues

2) Im all for you having your name on the pypi package, this was a lot of your work. Me and @abhinavk99  dont have as much free time as in the past but am happy to comment here if/when needed

**Comment by Chris-Peterson444** [comment]
Okay great. I appreciate the advice, thank you. I'll put your suggestion in the readme. Otherwise, I think I have everything ready to go. I'll make a PR and wait for @abhinavk99 to respond on the authorship point before merging.

**Comment by abhinavk99** [comment]
@Chris-Peterson444 Jikanpy v4 is mainly your work so I also think you should be the author on pypi. As @seanbreckenridge mentioned, I’m busier these days but I can help with small things.

**Comment by Chris-Peterson444** [comment]
jikanpy_v4 is now available on pypi: https://pypi.org/project/jikanpy-v4/ 

I'll update the badges in the readme in a sec, although pypi still shows outdated statistics for now.

bumping @BisericaOrtodoxa since you asked earlier in #105
